require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CandidatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Candidate. As you add validations to Candidate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    #skip("Add a hash of attributes valid for your model")
    {first_name: "Marisol", last_name: "Langworth", dob: "1991-05-17", gender: "T", marital_status: "unmarried", status: true, languages: "ipsum,error,possimus", summary: "Deleniti qui est quasi alias eum omnis harum. Aut ..."}
  }

  let(:invalid_attributes) {
    {first_name: "Marisol", last_name: "Langworth", dob: nil, gender: nil, marital_status: "unmarried", status: true, languages: "ipsum,error,possimus", summary: "Deleniti qui est quasi alias eum omnis harum. Aut ..."}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CandidatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before do
    @candidate = FactoryGirl.create(:candidate)
    sign_in @candidate.user
    allow_any_instance_of(CanCan::ControllerResource).to receive(:load_and_authorize_resource){ nil } 
  end

  describe "GET #index" do
    it "assigns all candidates as @candidates" do
      get :index
      expect(assigns(:candidates)).to eq([@candidate])
    end
  end

  describe "GET #show" do
    it "assigns the requested candidate as @candidate" do
      get :show, id: @candidate.id
      expect(assigns(:candidate)).to eq(@candidate)
    end
  end

  describe "GET #new" do
    it "assigns a new candidate as @candidate" do
      get :new, params: {}, session: valid_session
      expect(assigns(:candidate)).to be_a_new(Candidate)
    end
  end

  describe "GET #edit" do
    it "assigns the requested candidate as @candidate" do
      get :edit, id: @candidate.id
      expect(assigns(:candidate)).to eq(@candidate)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Candidate" do
        expect {
          post :create, candidate: valid_attributes
        }.to change(Candidate, :count).by(1)
      end

      it "assigns a newly created candidate as @candidate" do
        post :create, candidate: valid_attributes
        expect(assigns(:candidate)).to be_a(Candidate)
        expect(assigns(:candidate)).to be_persisted
      end

      it "redirects to the created candidates home" do
        post :create, candidate: valid_attributes
        expect(response).to redirect_to(home_candidate_path(Candidate.last))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved candidate as @candidate" do
        post :create, candidate: invalid_attributes
        expect(assigns(:candidate)).to be_a_new(Candidate)
      end

      it "re-renders the 'new' template" do
        post :create, candidate: invalid_attributes
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
 {first_name: "Marisol", last_name: "Doe", dob: "1991-05-17", gender: "T", marital_status: "unmarried", status: true, languages: "ipsum,error,possimus", summary: "Deleniti qui est quasi alias eum omnis harum. Aut ..."} 
      }

      it "updates the requested candidate" do
        put :update, id: @candidate.id, candidate: new_attributes
        @candidate.reload
        expect(@candidate.last_name).to eq("Doe")
      end

      it "assigns the requested candidate as @candidate" do
        put :update, id: @candidate.id, candidate: valid_attributes
        expect(assigns(:candidate)).to eq(@candidate)
      end

      it "redirects to the edit candidate again" do
        put :update, id: @candidate.id, candidate: valid_attributes
        expect(response).to redirect_to(edit_candidate_path(@candidate))
      end
    end

    context "with invalid params" do
      it "assigns the candidate as @candidate" do
        put :update, id: @candidate.id, candidate: invalid_attributes
        expect(assigns(:candidate)).to eq(@candidate)
      end

      it "re-renders the 'edit' template" do
        put :update, id: @candidate.id, candidate: invalid_attributes
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested candidate" do
      expect {
        delete :destroy, id: @candidate.id
      }.to change(Candidate, :count).by(-1)
    end

    it "redirects to the candidates list" do
      delete :destroy, id: @candidate.id
      expect(response).to redirect_to(candidates_url)
    end
  end

end
